#!/bin/sh
#####Fred Cook#####
# Set our default path
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin/core_perl:/usr/bin:$HOME/.config/bspwm/panel:$HOME/.bin:$HOME/.scripts:/home/$USER/.dotnet/tools"

export PATH
export XDG_CONFIG_HOME="$HOME/.config"
export BROWSER=/usr/bin/firefox
export TERMINAL=/usr/bin/alacritty
export QT_QPA_PLATFORMTHEME="qt5ct"
export EDITOR=/usr/bin/nvim
export VISUAL=/usr/bin/code
export READER=/usr/bin/zathura
export FILES=/usr/bin/vifm
export VIDEO=/usr/bin/vlc
export SHELL=/usr/bin/zsh

#### AUTOSTART ####
sxhkd &
nitrogen --restore &
redshift -c ~/.config/redshift.conf &
xfce4-power-manager &
~/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom.conf &
nm-applet &
unclutter --timeout 4 &
pidof bspswallow || bspswallow &
spotify-listener & 
#### MONITORS ####
~/.scripts/bspc_monitor_startup &
~/.scripts/desktop_or_laptop &
setxkbmap -option caps:swapescape &
alacritty -e ~/.scripts/toggletdrop &
xsetroot -cursor_name left_ptr &

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  5
bspc config window_gap                    10
bspc config top_padding                   35
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		 	"#4c566a"
bspc config active_border_color        	"#6272a4"
bspc config focused_border_color   		"#8be9fd"
bspc config presel_feedback_color		"#5e81ac"
bspc config urgent_border_color 		"#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a "*doom* - Doom Emacs" state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a * state=tiled
bspc rule -a Steam state=tiled
bspc rule -a Steam focus=off
bspc rule -a dota2 state=tiled
bspc rule -a "Ball Physics Simulator" state=floating


bspc rule -a dropdown sticky=on state=floating hidden=on
alacritty --class dropdown -e "zsh -i" &

/bin/bash -c "sleep 10&&dropbox start -i" &
