#!/bin/bash

if [ -n "$1" ]; then
	filepath=$1
else
	#default filepath, normally used
	filepath="/home/$USER/dotfiles/VSCodium/.config/VSCodium/User/extensions.list"
fi

cat $filepath | grep -v '^#' | xargs -L1 code --install-extension
#< $filepath xargs -I % codium --install-extension %
